global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bandwidth_monitor'
    scrape_interval: 15m
    scrape_timeout: 30s
    static_configs:
      - targets: ['bandwidth_monitor:9180']

