{
 "title": "Bandwidth usage",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Data down per device in a range",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(bytes_down[$__range])/1048576 != 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Data up per device in a range",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(bytes_up[$__range])/1048576 != 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Data down",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "bytes_down / 1048576 != 0", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Data up",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "bytes_up / 1048576 != 0", "legendFormat": "{{name}}" }
   ]
  }
 ]
}