name: Publish Docker Image

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jagub2/mikrotik_bandwidth_monitor_exporter:latest
    - name: Login to the Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Publish the Docker image
      run: docker push jagub2/mikrotik_bandwidth_monitor_exporter:latest
